-- ═══════════════════════════════════════════════════════════════════════
-- Migration 023: orders, portal_users, lab_reports tables
-- ═══════════════════════════════════════════════════════════════════════

-- ── portal_users: pharmacy & lab portal login accounts ───────────────
CREATE TABLE IF NOT EXISTS portal_users (
    id           UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username     VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    portal_type  VARCHAR(20) NOT NULL CHECK (portal_type IN ('pharmacy', 'lab')),
    name         VARCHAR(255) NOT NULL,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE portal_users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON portal_users FOR ALL USING (true) WITH CHECK (true);

-- Seed portal users (bcrypt hashes for Pharmacy@123 and Lab@123)
INSERT INTO portal_users (username, password_hash, portal_type, name) VALUES
(
  'medivora_pharmacy',
  '$2b$12$8TJP6g.XAClw37wn26Ljd.UnYhQUOeGHpADRXHNYkvvcsSuUjq44C',
  'pharmacy',
  'Medivora Pharmacy'
),
(
  'medivora_lab',
  '$2b$12$CYxWCoi54GijCo1opZXA0OZ9qBjihRs9P9MHJBI9OwfDWWWB5i6Fy',
  'lab',
  'Medivora Diagnostics Lab'
)
ON CONFLICT (username) DO NOTHING;

-- ── orders: pharmacy and lab orders ─────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    type             VARCHAR(20) NOT NULL CHECK (type IN ('pharmacy', 'lab')),
    patient_id       UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    prescription_id  UUID REFERENCES prescriptions(id) ON DELETE SET NULL,
    status           VARCHAR(30) NOT NULL DEFAULT 'pending'
                       CHECK (status IN (
                         'pending', 'confirmed', 'processing',
                         'out_for_delivery', 'delivered', 'completed',
                         'sample_collected', 'report_ready', 'cancelled'
                       )),
    items            JSONB NOT NULL DEFAULT '[]',
    delivery_type    VARCHAR(20) DEFAULT 'home'
                       CHECK (delivery_type IN ('home', 'visit')),
    delivery_address TEXT,
    notes            TEXT,
    total_amount     DECIMAL(10,2),
    invoice_data     JSONB,
    report_url       TEXT,
    report_notes     TEXT,
    portal_notes     TEXT,
    patient_name     TEXT,
    patient_phone    TEXT,
    created_at       TIMESTAMPTZ DEFAULT NOW(),
    updated_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_patient ON orders(patient_id);
CREATE INDEX IF NOT EXISTS idx_orders_type ON orders(type);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_prescription ON orders(prescription_id);

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON orders FOR ALL USING (true) WITH CHECK (true);

-- ── lab_reports: reports generated by lab and shared to patient ──────
CREATE TABLE IF NOT EXISTS lab_reports (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    order_id    UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    patient_id  UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    test_names  TEXT,
    report_url  TEXT,
    report_notes TEXT,
    shared_at   TIMESTAMPTZ,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_lab_reports_order ON lab_reports(order_id);
CREATE INDEX IF NOT EXISTS idx_lab_reports_patient ON lab_reports(patient_id);

ALTER TABLE lab_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service role full access" ON lab_reports FOR ALL USING (true) WITH CHECK (true);
